@password = c8105dd8-008e-4248-a7d4-044553f1fe19
@token = Basic user:{{password}}

### @name getUsers
GET /users HTTP/1.1
Host: localhost:8080
Authorization: {{token}}

### @name getUsersInternational
GET /users-international HTTP/1.1
Host: localhost:8080
Accept-Language: en
Authorization: {{token}}

### @name getUser
GET /users/1 HTTP/1.1
Host: localhost:8080
Authorization: {{token}}

### @name getUserXml
GET /users/1 HTTP/1.1
Host: localhost:8080
Accept: application/xml
Authorization: {{token}}

### @name getUserNegative
GET /users/123456 HTTP/1.1
Host: localhost:8080
Authorization: {{token}}

### @name postUser
POST /users HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Bob Smith",
    "dob": "2021-09-06T10:13:31.551+00:00"
}

### @name postUserXml
POST /users HTTP/1.1
Host: localhost:8080
Content-Type: application/xml
Authorization: {{token}}

<?xml version="1.0" encoding="UTF-8" ?>
<root>
  <name>Bob Smith</name>
  <dob>2021-09-06T10:13:31.551+00:00</dob>
</root>

### @name postUserNegative
POST /users HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: {{token}}

{
    "name": "",
    "dob": "2021-09-05T10:13:31.551+00:00"
}

### @name deleteUser
DELETE /users/5 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: {{token}}

### @name deleteUserNegative
DELETE /users/1234 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: {{token}}

### @name getUserPosts
GET /users/1/posts HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: {{token}}

### @name postUserPost
POST /users/1/posts HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: {{token}}

{
    "description": "THIS IS A TEST POST!"
}

### @name getUserPostDetails
GET /users/1/posts/1 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: {{token}}